import { Request, Response } from "express";


// DATA REFLECTED ON JUN 28 2026
export const COLLEGES = [
    { value: "CAD",   label: "College of Art and Design" },
    { value: "SCB",   label: "Saunders College of Business" },
    { value: "GCCIS", label: "Golisano College of Computer and Information Sciences" },
    { value: "KGCOE", label: "Kate Gleason College of Engineering" },
    { value: "CET",   label: "College of Engineering Technology" },
    { value: "CHST",  label: "College of Health Sciences and Technology" },
    { value: "CLA",   label: "College of Liberal Arts" },
    { value: "NTID",  label: "National Technical Institute for the Deaf" },
    { value: "COS",   label: "College of Science" },
    { value: "GIS",   label: "Golisano Institute for Sustainability" },
    { value: "INTSD", label: "School of Interdisciplinary Studies" },
    { value: "STUAF", label: "Student Affairs Division" },
]

export const SUBJECTS = [
    { value: "ACBS", label: "Accounting & Business Systems" },
    { value: "ACCT", label: "Accounting" },
    { value: "ACDS", label: "Academic Success Center" },
    { value: "ACSC", label: "Academic Success Center in Student Affairs" },
    { value: "AERO", label: "Aerospace Studies" },
    { value: "ANTH", label: "Anthropology" },
    { value: "ARCH", label: "Architecture" },
    { value: "ARED", label: "Art Education" },
    { value: "ARMY", label: "Reserve Officer Training-Army" },
    { value: "ARTH", label: "Art History" },
    { value: "ARTX", label: "Art Experience" },
    { value: "ASLC", label: "ASL/Deaf Culture" },
    { value: "ASTP", label: "Astrophysical Sciences & Tech" },
    { value: "BANA", label: "Business Analytics" },
    { value: "BCEP", label: "Biomed & Chemical Engineering PhD" },
    { value: "BHNS", label: "Behavioral Health and Neuroscience" },
    { value: "BIME", label: "Biomedical Engineering" },
    { value: "BIOG", label: "Biology Non-Majors" },
    { value: "BIOL", label: "Biology" },
    { value: "BLEG", label: "Business Legal Studies" },
    { value: "BTRM", label: "Better Me-Employee Wellness" },
    { value: "CCER", label: "Ceramics" },
    { value: "CGLS", label: "Glass" },
    { value: "CGNS", label: "Applied Cognitive Neuroscience" },
    { value: "CHEM", label: "Chemistry" },
    { value: "CHMA", label: "Analytical Chemistry" },
    { value: "CHMB", label: "Bio Chemistry" },
    { value: "CHME", label: "Chemical Engineering" },
    { value: "CHMG", label: "General Chemistry" },
    { value: "CHMI", label: "Inorganic Chemistry" },
    { value: "CHMO", label: "Organic Chemistry" },
    { value: "CHMP", label: "Physical Chemistry" },
    { value: "CHPO", label: "Polymer Chemistry" },
    { value: "CINT", label: "Computing Intra-College Studies" },
    { value: "CISC", label: "Computing & Info Sciences-PhD" },
    { value: "CLRS", label: "Color Science" },
    { value: "CMPE", label: "Computer Engineering" },
    { value: "CMPR", label: "Computer Programming-KGCOE" },
    { value: "CMTJ", label: "Metal & Jewelry Design" },
    { value: "COGS", label: "Cognitive Science" },
    { value: "COMM", label: "Communication" },
    { value: "CONM", label: "Construction Management" },
    { value: "CPET", label: "Computer Engineering Technology" },
    { value: "CQAS", label: "Quality & Applied Statistics" },
    { value: "CRIM", label: "Criminal Justice" },
    { value: "CSCI", label: "Computer Science" },
    { value: "CSEC", label: "Cybersecurity" },
    { value: "CVET", label: "Civil Engineering Technology" },
    { value: "CWFD", label: "Furniture Design" },
    { value: "CWTD", label: "Weaving & Textile Design" },
    { value: "DCHP", label: "Department of Clinical Health Professions" },
    { value: "DDDD", label: "3D Digital Design" },
    { value: "DEAF", label: "DEAF" },
    { value: "DECS", label: "Decision Sciences" },
    { value: "DHSS", label: "Digital Humanities & Social Sciences" },
    { value: "DMSO", label: "Diagnostic Med Sonography" },
    { value: "DSCI", label: "Data Science" },
    { value: "ECEP", label: "Electrical & Computer Engineering PhD" },
    { value: "ECHO", label: "Echocardiography" },
    { value: "ECON", label: "Economics" },
    { value: "EDGE", label: "EDGE" },
    { value: "EDLI", label: "Education Learning Instruction" },
    { value: "EEEE", label: "Electrical Engineering" },
    { value: "EEET", label: "Electrical Engineering Technology" },
    { value: "EGEN", label: "General Engineering" },
    { value: "ELCA", label: "ELC-Academic Purposes" },
    { value: "ELCI", label: "ELC-Intensive Program for Beg & Intermed" },
    { value: "ENGL", label: "English" },
    { value: "ENGR", label: "Engineering - PhD program courses" },
    { value: "ENGT", label: "Engineering Technology" },
    { value: "ENVS", label: "Environmental Science" },
    { value: "ESCB", label: "Economics (COB)" },
    { value: "ESHS", label: "Environmental Sustainability Health & Safety Mgt" },
    { value: "EXSC", label: "Exercise Science" },
    { value: "FDTN", label: "Foundation Courses" },
    { value: "FINC", label: "Finance" },
    { value: "FNAS", label: "Fine Art Studio" },
    { value: "FNRT", label: "Fine Arts" },
    { value: "GAMA", label: "Game Arts (CAD)" },
    { value: "GCIS", label: "GCCIS College Level Courses" },
    { value: "GEPR", label: "General Education Perspectives" },
    { value: "GLPH", label: "Global Public Health" },
    { value: "GRCS", label: "CET Graduate Courses" },
    { value: "GRDE", label: "Graphic Design - Undergraduate" },
    { value: "GSCI", label: "General Science Exploration" },
    { value: "HCIA", label: "Health Care Interpretation" },
    { value: "HCIN", label: "Human Computer Interaction" },
    { value: "HIST", label: "History" },
    { value: "HLTH", label: "Health Systems Management" },
    { value: "HNRS", label: "Honors Program" },
    { value: "HRDE", label: "Human Resource Development" },
    { value: "HSPT", label: "Hospitality & Tourism" },
    { value: "IDAI", label: "Artificial Intelligence (Interdisciplinary)" },
    { value: "IDDE", label: "Industrial Design" },
    { value: "IDEA", label: "Interdisciplinary Art, Design, Photo" },
    { value: "IGME", label: "Interactive Games & Media" },
    { value: "ILLM", label: "Medical Illustration" },
    { value: "ILLS", label: "Illustration" },
    { value: "IMGS", label: "Imaging Science" },
    { value: "IMSM", label: "Imaging Systems Management" },
    { value: "INDE", label: "Interior Design" },
    { value: "INGD", label: "Integrative Design" },
    { value: "INGS", label: "International & Global Studies" },
    { value: "INTB", label: "International Business" },
    { value: "INTP", label: "ASL-English Interpretation" },
    { value: "INTS", label: "Integrated Sciences" },
    { value: "ISCH", label: "School of Information" },
    { value: "ISEE", label: "Industrial & Systems Engineering" },
    { value: "ISTE", label: "Information Sciences & Technologies" },
    { value: "ISUS", label: "Institute for Sustainability" },
    { value: "ITDI", label: "Interdisciplinary Imaging Arts" },
    { value: "ITDL", label: "Interdisciplinary-Liberal Arts" },
    { value: "ITDS", label: "Interdisciplinary Science" },
    { value: "LEAD", label: "Community Development and Inclusive Leadership" },
    { value: "LING", label: "Linguistics" },
    { value: "MAAT", label: "Media Arts & Technology" },
    { value: "MATH", label: "Mathematics" },
    { value: "MCEE", label: "Microelectronic Engineering" },
    { value: "MCET", label: "Mechanical Engineering Technology" },
    { value: "MCSE", label: "Microsystems Engineering" },
    { value: "MECA", label: "Mechatronics Engineering Technology" },
    { value: "MECE", label: "Mechanical Engineering" },
    { value: "MEDG", label: "Medical Sciences - General" },
    { value: "MEDI", label: "Medical Informatics" },
    { value: "MEDS", label: "Medical Sciences" },
    { value: "MGIS", label: "Management Information Systems" },
    { value: "MGMT", label: "Management" },
    { value: "MIEP", label: "Mechanical & Industrial Engineering PhD" },
    { value: "MKTG", label: "Marketing" },
    { value: "MLAR", label: "Modern Language-Arabic" },
    { value: "MLAS", label: "Modern Language-American Sign" },
    { value: "MLCH", label: "Modern Language-Chinese" },
    { value: "MLCU", label: "Modern Languages & Cultures" },
    { value: "MLFR", label: "Modern Language-French" },
    { value: "MLGR", label: "Modern Language-German" },
    { value: "MLIT", label: "Modern Language-Italian" },
    { value: "MLJP", label: "Modern Language-Japanese" },
    { value: "MLPO", label: "Modern Language-Portuguese" },
    { value: "MLRU", label: "Modern Language-Russian" },
    { value: "MLSP", label: "Modern Language-Spanish" },
    { value: "MLST", label: "Modern Language-Special Topics" },
    { value: "MSSE", label: "NTID MS in Secondary Education" },
    { value: "MTSC", label: "Math & Science (INTSD)" },
    { value: "MTSE", label: "Materials Science & Engineering" },
    { value: "MUSE", label: "Museum Studies" },
    { value: "N3DG", label: "3D Graphics Technology" },
    { value: "NACA", label: "NTID AS Applied Computer Programming" },
    { value: "NACC", label: "Accounting Technology" },
    { value: "NACT", label: "ACT Technical Computing Courses" },
    { value: "NAIS", label: "General Visual Communications Courses" },
    { value: "NASL", label: "Sign Languages" },
    { value: "NAST", label: "Administrative Support Technology" },
    { value: "NBUS", label: "General Business" },
    { value: "NCAD", label: "Computer Aided Drafting Technology" },
    { value: "NCAR", label: "Career Development" },
    { value: "NCIM", label: "CIMT-Computer Integrated Mach Tech" },
    { value: "NCOM", label: "Communications Studies" },
    { value: "NDLS", label: "NTID Department of Liberal Studies" },
    { value: "NENG", label: "English (NTID)" },
    { value: "NETS", label: "General Engineering Studies Courses" },
    { value: "NGRD", label: "Graphic Design Concentration Courses" },
    { value: "NGRP", label: "Graphic Production Concentration Courses" },
    { value: "NHSS", label: "Humanities & Social Sciences" },
    { value: "NINT", label: "NINT" },
    { value: "NLST", label: "Laboratory Science Technology" },
    { value: "NMAD", label: "Mobile Application Development" },
    { value: "NMDE", label: "New Media Design" },
    { value: "NMTH", label: "Mathematics (NTID)" },
    { value: "NPMT", label: "NTID Precision Manufacturing Technology" },
    { value: "NSCI", label: "Science (NTID)" },
    { value: "NSSA", label: "Networking, Security & Systems Administration" },
    { value: "NSVP", label: "Summer Vestibule Experience" },
    { value: "NUTR", label: "Nutrition" },
    { value: "OCTH", label: "Occupational Therapy" },
    { value: "PACK", label: "Packaging Science" },
    { value: "PAIT", label: "Painting" },
    { value: "PHAP", label: "Advertising Photography" },
    { value: "PHAR", label: "Photographic Arts" },
    { value: "PHFA", label: "Fine Art Photo" },
    { value: "PHGR", label: "Photography - Graduate" },
    { value: "PHIL", label: "Philosophy" },
    { value: "PHMS", label: "Photo Media Science" },
    { value: "PHPJ", label: "Photojournalism" },
    { value: "PHPS", label: "Photographic Sciences" },
    { value: "PHVM", label: "Photo Visual Media" },
    { value: "PHYA", label: "Physician Assistant" },
    { value: "PHYS", label: "Physics" },
    { value: "PLTW", label: "Project Lead the Way" },
    { value: "PMED", label: "Premed Studies" },
    { value: "POLS", label: "Political Science" },
    { value: "PPRT", label: "Print Media" },
    { value: "PRFL", label: "Performing Arts Liberal Arts" },
    { value: "PRFN", label: "Performing Arts NTID" },
    { value: "PRNT", label: "Printmaking" },
    { value: "PROF", label: "Professional Studies" },
    { value: "PSYC", label: "Psychology" },
    { value: "PUBL", label: "Public Policy" },
    { value: "RMET", label: "Robotics and Manufacturing Engineering Technology" },
    { value: "SAB",  label: "Study Abroad" },
    { value: "SCBI", label: "Business Interdisciplinary" },
    { value: "SCUL", label: "Sculpture" },
    { value: "SECU", label: "Security Technology" },
    { value: "SERQ", label: "Service Quality Management" },
    { value: "SOCI", label: "Sociology" },
    { value: "SOFA", label: "Film & Animation" },
    { value: "SOIS", label: "School of Individualized Study" },
    { value: "SPSY", label: "School Psychology" },
    { value: "STAR", label: "Studio Arts" },
    { value: "STAT", label: "Statistics" },
    { value: "STSO", label: "Science, Technology & Society" },
    { value: "SWEN", label: "Software Engineering" },
    { value: "TCET", label: "Telecommunications Engineering Technology" },
    { value: "TCOM", label: "Tech Communications" },
    { value: "UWRT", label: "University Writing" },
    { value: "UXDE", label: "User Experience & Design" },
    { value: "VCDE", label: "Visual Communication Design-Grad" },
    { value: "VISL", label: "Visual Culture" },
    { value: "WDAN", label: "Dance" },
    { value: "WFIT", label: "Fitness" },
    { value: "WGST", label: "Women's, Gender, and Sexuality Studies" },
    { value: "WHLS", label: "Health & Safety" },
    { value: "WHWS", label: "Health & Wellness Seminars" },
    { value: "WINT", label: "Outdoor Education" },
    { value: "WMAR", label: "Martial Arts" },
    { value: "WMIL", label: "Military Sciences" },
    { value: "WMUS", label: "Wellness Music" },
    { value: "WREC", label: "Lifetime Rec Activities" },
    { value: "WSHN", label: "Wegmans School of Health & Nutrition" },
    { value: "YOPS", label: "Year One Programs" },
]

export const GRADUATE_TYPES = [
    { value: "coursetype_ugrad", label: "Undergraduate" },
    { value: "coursetype_grad", label: "Graduate" },
]

export const PERSPECTIVES = [
    { value: "perspectives_ARTISTIC",    label: "Artistic Perspective" },
    { value: "perspectives_ETHICAL",     label: "Ethical Perspective" },
    { value: "perspectives_GLOBAL",      label: "Global Perspective" },
    { value: "perspectives_MATHEMATIC",  label: "Mathematical Perspective" },
    { value: "perspectives_NATSCI_INQ",  label: "Natural Science Inquiry Perspective" },
    { value: "perspectives_SCIE_PRIN",   label: "Scientific Principles Perspective" },
    { value: "perspectives_SOCIAL",      label: "Social Perspective" },
]

export const GET = async (_req: Request, res: Response) => {
    return res.json({ colleges: COLLEGES, graduateTypes: GRADUATE_TYPES, subjects: SUBJECTS, perspectives: PERSPECTIVES });
};
